### ISSUE TITLE
Upgrade to DKPro Core Parent Pom 14

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core-examples#11]
cf. https://github.com/dkpro/dkpro-core/issues/824

**Comment by carschno** [comment]
[ERROR]     Non-resolvable parent POM for org.dkpro:dkpro-core-examples:1.8.0-SNAPSHOT: Could not transfer artifact org.dkpro:dkpro-parent-pom:pom:14 from/to ukp-central (https://scruffy.ukp.informatik.tu-darmstadt.de/artifactory/ukp-internal-grid): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ line 31, column 11 -> [Help 2]

**Comment by reckart** [comment]
It takes a bit after a release until the artifact is available on Maven Central. Try again later.

**Comment by carschno** [comment]
With my Maven settings, the problem seems to be that the SSL certificate of Scruffy cannot be verified. The POM is now there (https://scruffy.ukp.informatik.tu-darmstadt.de/artifactory/ukp-internal-grid/org/dkpro/dkpro-parent-pom/14/), but I am unable to download it even with wget (unless I deactivate the certificate checks):

    $ wget https://scruffy.ukp.informatik.tu-darmstadt.de/artifactory/ukp-internal-grid/org/dkpro/dkpro-parent-pom/14/dkpro-parent-pom-14.pom--2016-04-14 14:11:11--  https://scruffy.ukp.informatik.tu-darmstadt.de/artifactory/ukp-internal-grid/org/dkpro/dkpro-parent-pom/14/dkpro-parent-pom-14.pom
    Resolving scruffy.ukp.informatik.tu-darmstadt.de (scruffy.ukp.informatik.tu-darmstadt.de)... 130.83.167.141
    Connecting to scruffy.ukp.informatik.tu-darmstadt.de (scruffy.ukp.informatik.tu-darmstadt.de)|130.83.167.141|:443... connected.
    ERROR: cannot verify scruffy.ukp.informatik.tu-darmstadt.de's certificate, issued by 'emailAddress=tud-ca@hrz.tu-darmstadt.de,CN=TUD CA G01,O=Technische Universitaet Darmstadt,L=Darmstadt,ST=Hessen,C=DE':
      Unable to locally verify the issuer's authority.
    To connect to scruffy.ukp.informatik.tu-darmstadt.de insecurely, use `--no-check-certificate'.

I suppose this should not be a problem when using Maven Central, but I am logging this in case something is wrong with our certificate (expired?).
