### ISSUE TITLE
Error in Eclipse: Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by ruslanrf** [dkpro/dkpro-core-examples#21]
It seems that the issue is related to the e2m plug-in and appears for pom files of sub-projects (e.g. `nameannotation-asl`).
Error text:
```
Description Resource  Path  Location  Type
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:build-helper-maven-plugin:1.8:add-source (execution: addToSourceFolder, phase: process-sources)  pom.xml /nameannotation-asl line 21 Maven Project Build Lifecycle Mapping Problem
```

**Comment by carschno** [comment]
Dear @ruslanrf, thanks for reporting this issue. Since I do not use Eclipse myself, could you provide some more details about the context in which this error occurs?

**Comment by reckart** [comment]
I don't have that problem in my Eclipse. I believe that there is a standard m2e connector for the build-helper plugin that Eclipse can automatically discover and install. 

@ruslanrf try hovering with the mouse over the marker in the POM and I believe there should be a popup appearing where you can choose to install a plugin/connector to fix the warning.
