### ISSUE TITLE
Jenkins is unable to find valid certification path

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core-examples#25]
Jenkins issues the following error:

    [ERROR] Failed to execute goal on project stanfordcorecomponents-gpl: Could not resolve dependencies for project org.dkpro:stanfordcorecomponents-gpl:jar:1.9.0-SNAPSHOT: Failed to collect dependencies at de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-gpl:jar:1.9.0-SNAPSHOT -> edu.stanford.nlp:stanford-corenlp:jar:3.7.0-beta-1: Failed to read artifact descriptor for edu.stanford.nlp:stanford-corenlp:jar:3.7.0-beta-1: Could not transfer artifact edu.stanford.nlp:stanford-corenlp:pom:3.7.0-beta-1 from/to ukp-oss (https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ext-releases-local): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :stanfordcorecomponents-gpl

I had the same error locally before installing the new SSL certificate of our internal Maven server. I am not sure whether this problem is rooted in the same cause. @reckart ?

**Comment by carschno** [comment]
I guess that the artifact `edu.stanford.nlp:stanford-corenlp:jar:3.7.0-beta-1` is not publicly available in the repositories configured in the Pom. I wonder which repository should be added.

**Comment by reckart** [comment]
```
<!-- Repository declaration temporarily needed until CoreNLP is available from Maven Central -->  
  <repositories>
    <repository>
      <id>ukp-oss</id>
      <name>ukp-oss-releases</name>
      <url>https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ext-releases-local</url>
    </repository>
  </repositories>
```

**Comment by carschno** [comment]
I had actually added that repository to the root pom file in 5c410cf. Moving it to the module's pom file (in 553ef0e) did not help (probably to be expected). The error remains the same as previously; I suppose there is an issue with respect to the SSL certificate.

**Comment by reckart** [comment]
The DKPro Core build runs nicely on Jenkins - thus the DKPro Cor Examples build should also not have a problem.

**Comment by reckart** [comment]
You could try replacing the `https` URL with a `http` URL.

**Comment by luomingui** [comment]
Tips for installing plug-ins
unable to find valid certification path to requested target
