### ISSUE TITLE
Convert into multi-module project ASL/GPL

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core-examples#4]
Updated (09/11/15):
Create modules for each existing example and move examples.

* [x] lda-asl
* [x] tokenizedwriter-asl
* [x] nameannotatro-asl
* [x] stanfordcorecomponents-gpl

**Comment by reckart** [comment]
How about one module per example instead of multiple examples per asl/gpl module?

**Comment by zesch** [comment]
+1 for @reckart 's suggestion

**Comment by carschno** [comment]
Sound ok to me. I.e.

```
dkpro-core-examples
    lda-asl
    ...
    stanfordcorecomponent-gpl
    ...
```
