### ISSUE TITLE
Change parent POM to dkpro-parent-pom

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core-examples#6]
According to best practice, the parent pom should not be dkpro-core, but dkpro-parent-pom:

    <parent>
      <groupId>org.dkpro</groupId>
      <artifactId>dkpro-parent-pom</artifactId>
      <version>13-SNAPSHOT</version>
    </parent>

**Comment by carschno** [comment]
This does not really seem to be a good idea because the version and groupid should be aligned to the dkpro-core project.

**Comment by reckart** [comment]
You can override the groupId - and I think the groupId here should be the something like "org.dkpro.core.examples"?

**Comment by carschno** [comment]
What is the general strategy here anyway? Is Dkpro (core) eventually going to adopt org.dkpro as well?

**Comment by reckart** [comment]
Yep - it's just a matter of somebody updating all the groupIds in DKPro Core ;)

**Comment by carschno** [comment]
OK, in that case it makes more sense.

**Comment by carschno** [comment]
Since version 13-SNAPSHOT is not available on Maven Central, I've set this parent POM to version 12.
